---
- name: Install apache and php packages
  apt: 
    name: ['apache2', 'php', 'php-mysql', 'libapache2-mod-php']
    state: present

- name: Install PHP Extensions
  apt: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"

- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'

- name: Set up Apache VirtualHost
  template:
    src: "apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
  notify: Reload Apache

- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite
  notify: Reload Apache

- name: Enable ldap module
  shell: /usr/sbin/a2enmod authnz_ldap
  notify: Reload Apache

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: Reload Apache

- name: Copy .htaccess file
  copy:
    src: .htaccess
    dest: "/var/www/{{ http_host }}/.htaccess"

- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: Restart Apache
