---
- name: Install prerequisites
  apt: 
      name: aptitude 
      update_cache: yes 
      state: latest 
      force_apt_get: yes

- name: Create a service user
  user:
    name: serviceuser

- name: Allow user to run systemctl/systemd services
  copy:
    src: serviceuser
    dest: /etc/sudoers.d/serviceuser
